name: Update OutdoorLads Calendar

on:
  schedule:
    - cron: '0 7 * * *'  # Every day at 7:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Generate outdoorlads.ics
        run: python generate_ics.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add outdoorlads.ics
          git commit -m "Update .ics calendar file" || echo "No changes to commit"
          git push
